In [ ]:
import torch

In [ ]:
# Number
t1 = torch.tensor(4.)
print(t1, t1.dtype, t1.shape)

tensor(4.) torch.float32 torch.Size([])


In [ ]:
# Vector
t2 = torch.tensor([1., 2, 3, 4]) # All elements of tensor has same type
print(t2, t2.dtype, t2.shape)

tensor([1., 2., 3., 4.]) torch.float32 torch.Size([4])


In [ ]:
# Matrix
t3 = torch.tensor([[5., 6],
                  [7, 8],
                   [9, 10]])
print(t3, t3.dtype, t3.shape)

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]]) torch.float32 torch.Size([3, 2])


In [ ]:
# 3d array
t4 = torch.tensor([[[11., 12., 13.],
                    [14., 15., 16]]])
print(t4, t4.dtype, t4.shape)

tensor([[[11., 12., 13.],
         [14., 15., 16.]]]) torch.float32 torch.Size([1, 2, 3])


In [ ]:
t5 = torch.tensor([
    [
        [1.,2.,3.],
        [4.,5.,6.]
    ],
    [
        [7.,8.,9.],
        [10.,11.,12.]
    ]
])
print(t5, t5.dtype, t5.shape)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]]) torch.float32 torch.Size([2, 2, 3])


Tensor must have a proper shape and same data type

In [ ]:
# create tensor
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
y = w*x+b
print(y)

tensor(17., grad_fn=<AddBackward0>)


We can automatically compute deivative w.r.t to tensors that have the 'requires_grad' parameter

In [ ]:
y.backward()

In [ ]:
print('dy/dx', x.grad)
print('dy/db', b.grad)
print('dy/dw', w.grad)

dy/dx None
dy/db tensor(1.)
dy/dw tensor(3.)


In [ ]:
# Create tensor with same values
t6 = torch.full((3,2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [ ]:
t7 = torch.cat((t3, t6), 1)  # 0 will stack  vertically and 1 will stack horizontally
t7

tensor([[ 5.,  6., 42., 42.],
        [ 7.,  8., 42., 42.],
        [ 9., 10., 42., 42.]])

In [ ]:
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794, -0.9165, -0.9165],
        [ 0.6570,  0.9894, -0.9165, -0.9165],
        [ 0.4121, -0.5440, -0.9165, -0.9165]])

In [ ]:
t9 = t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [-0.9165, -0.9165]],

        [[ 0.6570,  0.9894],
         [-0.9165, -0.9165]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]]])

In [ ]:
import numpy as np
x = np.array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
# convert numpy to torch tensor
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

## Gradient Descent and Linear Regression

In [ ]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-1.2797,  1.1569,  0.6113],
        [ 0.9261, -0.9310, -1.7667]], requires_grad=True)
tensor([-1.1898, -0.2488], requires_grad=True)


In [ ]:
def model(x):
    return x @ w.t() + b # @ is used for matrix multiplication. 't' is used for transpose

In [ ]:
preds = model(inputs)
print(preds)

tensor([[   9.1872,  -70.9919],
        [  23.2839, -110.9749],
        [  77.9502, -146.9059],
        [ -59.3566,  -11.1905],
        [  64.3600, -149.3974]], grad_fn=<AddBackward0>)


In [ ]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

torch.sum returns the sum of all the elements in a tensor. The .numel method of a tensor returns the number of elements in a tensor. Let's compute the mean squared error for the current predictions of our model.

In [ ]:
loss = mse(preds, targets)
print(loss)

tensor(23283.8477, grad_fn=<DivBackward0>)


In [ ]:
 loss.backward()

In [ ]:
print(w.grad) # derivative of loss wrt to w

tensor([[ -4641.0737,  -4184.7852,  -2760.5330],
        [-15473.7568, -18689.1953, -11286.8906]])


In [ ]:
with torch.no_grad(): # not tracking the gradient
  w-=w.grad*1e-5
  b-=b.grad*1e-5

In [ ]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(16336.5957, grad_fn=<DivBackward0>)


In [ ]:
# set gradients to 0 after computation is done
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [ ]:
for i in range(1000):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
loss = mse(preds, targets)
print(loss)

tensor(26.3291, grad_fn=<DivBackward0>)


## Linear Regression with PyTorch built-ins

In [ ]:
import torch.nn as nn

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
from torch.utils.data import TensorDataset

train_ds = TensorDataset(inputs, targets) # We'll create a TensorDataset, which allows access to rows from inputs and targets as tuples, and provides standard APIs for working with many different types of datasets in PyTorch.
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

The TensorDataset allows us to access a small section of the training data using the array indexing notation ([0:3] in the above code). It returns a tuple with two elements. The first element contains the input variables for the selected rows, and the second contains the targets.

We'll also create a DataLoader, which can split the data into batches of a predefined size while training. It also provides other utilities like shuffling and random sampling of the data.

In [ ]:
from torch.utils.data import DataLoader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True) # allows to input data in batches

for xb, yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 74.,  66.,  43.],
        [ 73.,  67.,  43.],
        [ 87., 134.,  58.],
        [ 87., 135.,  57.],
        [ 73.,  66.,  44.]])
tensor([[ 57.,  69.],
        [ 56.,  70.],
        [119., 133.],
        [118., 134.],
        [ 57.,  69.]])


In [ ]:
# define the model

model = nn.Linear(3,2) # (number of inputs, number of outputs)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[0.4914, 0.0441, 0.0520],
        [0.3688, 0.5165, 0.4977]], requires_grad=True)
Parameter containing:
tensor([-0.5440,  0.2387], requires_grad=True)


In [ ]:
preds = model(inputs)
preds

tensor([[ 40.5228,  83.1684],
        [ 51.3871, 111.1048],
        [ 51.1383, 130.4030],
        [ 53.4040,  78.4822],
        [ 41.2403, 110.1086],
        [ 40.9701,  83.0207],
        [ 51.3950, 111.0859],
        [ 51.6817, 131.2695],
        [ 52.9567,  78.6299],
        [ 40.8008, 110.2374],
        [ 40.5307,  83.1496],
        [ 51.8345, 110.9571],
        [ 51.1304, 130.4219],
        [ 53.8435,  78.3534],
        [ 40.7929, 110.2563]], grad_fn=<AddmmBackward0>)

In [ ]:
import torch.nn.functional as F
loss_fn = F.mse_loss

loss = loss_fn(model(inputs), targets)
print(loss)

tensor(1256.1497, grad_fn=<MseLossBackward0>)


In [ ]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
def fit(epochs, model, loss_fn, opt, train_dl):
  for epoch in range(epochs):
    for xb, yb in train_dl: # iterate over the batches
      preds = model(xb) # compute predictions
      loss = loss_fn(preds, yb) # compute loss
      loss.backward() # cmpute gradients
      opt.step() # use optimzer to update the parameters
      opt.zero_grad() # set gradients back to 0
    if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, epochs, loss.item()))

In [ ]:
fit(100, nn.Linear(3,2), loss_fn, opt, train_dl)

Epoch [10/100], Loss: 13613.7324
Epoch [20/100], Loss: 18858.5664
Epoch [30/100], Loss: 18104.9023
Epoch [40/100], Loss: 18129.0996
Epoch [50/100], Loss: 19475.8320
Epoch [60/100], Loss: 18926.2715
Epoch [70/100], Loss: 18319.4180
Epoch [80/100], Loss: 16938.7402
Epoch [90/100], Loss: 18246.9883
Epoch [100/100], Loss: 16410.5859
